version: "3"

services:
  streamlit:
    restart: always
    build: .
    tty: true
    volumes:
      - ./:/app
    command: /bin/sh -c "cd /app; pip install -r requirements.txt; streamlit run app.py;"
    ports:
      - 8501:8501